### ISSUE TITLE
update to match Font Awesome v4.7

### ISSUE THREAD

**Issue by m5o** [icons8/line-awesome#1]
I guess the Line Awesome is based on v4.4.0 version of FontAwesome.
What about push'in LineAwesome to match the latest FontAwesome release.

* http://fontawesome.io/icons/#new

**Comment by fitodac** [comment]
I took the liberty to update the icon library to Font Awesome 4.7.0. If the original project (Line Awesome) is not continued, I plan to update the icons by myself. Any help be appreciated.

Regards

**Comment by m5o** [comment]
@fitodac You should at least create a pull request with your changes to this repository. 

🔔 @Icons8-Team Are you interested? Sure!

**Comment by fitodac** [comment]
@m5o ok, I will treat to create a pull request in the next days. Thanks.

**Comment by jhit** [comment]
@fitodac How did you compile the font files? What was your workflow? I would like to change a icon too and offer my change as a pull request.

**Comment by fitodac** [comment]
@jhit Hi. With this app: https://birdfont.org/

**Comment by fitodac** [comment]
@m5o Sorry, I'm not totally familiarized with git, but made a pull request with an update to fontawesome 4.7.0.

**Comment by visualpharm** [comment]
With the recent release, are we ready to close it?
