### ISSUE TITLE
Question icon style is not consistent

### ISSUE THREAD

**Issue by Hongbo-Miao** [icons8/line-awesome#10]
Right now question icon is not consistent with other icons.
It would be great to change to simple `?`. Thanks

![image](https://user-images.githubusercontent.com/3375461/35788417-aab70e94-09e9-11e8-8ee9-84873d29086e.png)

![image](https://user-images.githubusercontent.com/3375461/35788379-6f979f54-09e9-11e8-8674-6f08c211f466.png)

![image](https://user-images.githubusercontent.com/3375461/35788343-25cb27b0-09e9-11e8-9d2c-b2d3b579ecff.png)

**Comment by fatawesome** [comment]
We've just released the new version of Line Awesome. If you still have the problem, feel free to contact us :)
