### ISSUE TITLE
question-circle size is not consistent with other xx-circle icons

### ISSUE THREAD

**Issue by Hongbo-Miao** [icons8/line-awesome#11]
![image](https://user-images.githubusercontent.com/3375461/35791294-00047208-09fc-11e8-9a7e-3cf3cdbcb1bc.png)

You can see from the screenshot, the size of question-circle is a little smaller than other xx-circle icons when set to same font-size.

**Comment by fatawesome** [comment]
Hello! We've just released the new version of Line Awesome. If you still have the problem, feel free to contact us 😊
