### ISSUE TITLE
fa-firefox and fa-cc-paypal wrong ??

### ISSUE THREAD

**Issue by JOduMonT** [icons8/line-awesome#13]
such as an example fa-firefox show linkedin icons
now I compared this [css](https://raw.githubusercontent.com/getgrav/grav-theme-quark/develop/css/line-awesome.min.css) with that [chart](https://fontawesome.com/icons?d=gallery&m=free)
and the unicode (f269) for firefox seams ok!

![screenshot_2018-04-09_09-42-29](https://user-images.githubusercontent.com/5204724/38485878-9ae6d6a6-3bdb-11e8-9c4b-b0709b00ba0b.png)

note : **fa-cc-paypal** also appear different as expected.

**Comment by fitodac** [comment]
Hi.
I fixed this and made a new pull-request.
Thanks

**Comment by fatawesome** [comment]
Hello! We've released an updated version of Line Awesome. Please, fill free to contact us if you have any problems.
