### ISSUE TITLE
Error on committing changes

### ISSUE THREAD

**Issue by fitodac** [icons8/line-awesome#14]
Hi @m5o
When commit, I get the following error:

git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags --set-upstream origin refs/heads/fix-wrong-icons:refs/heads/fix-wrong-icons 
Pushing to https://github.com/icons8/line-awesome
remote: Permission to icons8/line-awesome.git denied to fitodac.
fatal: unable to access 'https://github.com/icons8/line-awesome/': The requested URL returned error: 403
Completed with errors, see above

Could you help me with this?
Thanks

**Comment by m5o** [comment]
I guess you have to setup your origin and upstream first:

See https://help.github.com/articles/configuring-a-remote-for-a-fork/
