### ISSUE TITLE
Yarn Publish.

### ISSUE THREAD

**Issue by danielfreitas1** [icons8/line-awesome#18]
I tried to get the Line Awesome solution via Yarn from [this package](https://yarnpkg.com/pt-BR/package/line-awesome) and did not succeed. The package does not work and I really do not know what it's all about.

Is this the official package? If yes, could they ensure that it is functional?

In order to use the feature I created a second package in Yarn and called it "Line Awesome 2". You can see it [here](https://yarnpkg.com/pt-BR/package/line-awesome2). If that hurts the rules, I apologize. Otherwise, can we make it official?

If you tell me that the existing package works I remove my creation.

**Comment by fatawesome** [comment]
Hello! Recently we have released a new version of Line Awesome. Soon, for the simplicity of use, we will also publish the package to yarn. Feel free to contact us if you have any issues using Line Awesome 😊
