### ISSUE TITLE
CDN file doesn't contain .la class CSS

### ISSUE THREAD

**Issue by yashwp** [icons8/line-awesome#19]
I have included [<link rel="stylesheet" href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome-font-awesome.min.css">
](url) in my index.html, but when this file is downloaded to my browser, it does not have `.la` classes.
All it has is `.fa`. Henceforth the fonts are not working

**Comment by Kazuto** [comment]
So does the npm package which is very unfortunate if you want to use font-awesome and line-awesome alongside each other.

**Comment by fatawesome** [comment]
We have recently released the new version of Line Awesome! If you still have any issues feel free to contact us :blush:
