### ISSUE TITLE
Download link on 'How To' page broken

### ISSUE THREAD

**Issue by JordyValentine** [icons8/line-awesome#21]
The download link on the 'How To' page [https://icons8.com/line-awesome/howto](https://icons8.com/line-awesome/howto) returns a 404 error.

Is there an alternative? I'd prefer not to use the cdn in my project

**Comment by fatawesome** [comment]
Hello! It will be fixed in 30 mins, sorry for inconvenience 😞

**Comment by fatawesome** [comment]
Fixed, check it out! Thanks for contacting us :)

**Comment by JordyValentine** [comment]
Thanks @fatawesome
