### ISSUE TITLE
SCSS assets

### ISSUE THREAD

**Issue by dangelion** [icons8/line-awesome#23]
Hi
I can't find anymore the .scss files to include in my project. I need to import it in this way, in my main.scss:

```
$la-css-prefix: la;
@import "~line-awesome/src/line-awesome";
```

Now this doesn't work anymore.
Could help?
Thanks

**Comment by fatawesome** [comment]
Hello! It's true that we don't have .scss file anymore, but you can still import plain css file.

**Comment by dangelion** [comment]
Hi @fatawesome 
I think this is worse than before, because the common way to import a library in a modern project is with .scss, not compiled .css.
Also with .css we can't take advantage of variables override. 

This is a very very strange choice. I would strongly advice you to have back .scss? Is there any chance?
Thanks

**Comment by MildTomato** [comment]
Same here, surprised the scss support has gone.
I've not updated to the new version yet because of it.

The new icons are great though !

**Comment by fatawesome** [comment]
@dangelion @MildTomato thank you for feedback! We've decided to return scss support in upcoming updates. I will keep the issue open and notify when this feature will be added.

**Comment by dangelion** [comment]
@fatawesome Thank you for your answer. 

When you planned to have back .scss? Because we use LineAwesome in production projects and if you plan it far ahead we have to migrate to another library, unfortunately.

**Comment by fatawesome** [comment]
Sorry for late answer. We are planning to do a minor release till the middle of the week. We will try our best to include .scss lib in it.

**Comment by dangelion** [comment]
Thanks @fatawesome. We (as many others) really hope you can do that! 🙏 We love your library and would be a pity to migrate to another one.

**Comment by fatawesome** [comment]
Hey, we've added scss lib in 1.3.0! Archive on the site will be updated tommorow. Check it out, but be aware that it might not have full back compatibility with old scss (as the whole styles thing is completely new) and there might be some bugs. Feel free to open issues regarding to that.

**Comment by dangelion** [comment]
Love it! I'll check it out and let you know. Note that it's a bit strange to have source "scss" folder inside compiled "dist" folder.

**Comment by fatawesome** [comment]
Yeah, lack of structure, I know. But right now we needed to stick to it. Will be fixed later :)
