### ISSUE TITLE
facebook messenger doesn't work

### ISSUE THREAD

**Issue by carasmo** [icons8/line-awesome#24]
I added this to the last of the css to get it to work:

`.la.la-facebook-messenger {
  font-family: 'Line Awesome Brands';
  font-weight: 400; }`

**Comment by fatawesome** [comment]
Hello! Did you use it properly? Like this: `<i class="lab la-facebook-messenger"></i>`

**Comment by fatawesome** [comment]
Seems that everything is ok for now, so I'm closing this issue. If you have any questions please open a new one 😊
