### ISSUE TITLE
SVG files

### ISSUE THREAD

**Issue by hugobqd** [icons8/line-awesome#25]
Is it possible to have the SVG sources in the repo?
For some of us, inline SVG or linked SVG are preferred method rather than icon font.
Line-awesome is great, Thanks

**Comment by hugobqd** [comment]
I have found [this zip](https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.1.0/line-awesome-1.1.0.zip) containing the SVG on the [how to](https://icons8.com/line-awesome/howto). 
Having theses source on the github could make it easier to find

**Comment by fatawesome** [comment]
Sure, we will add them

**Comment by fatawesome** [comment]
Hello! We've added SVG files in 1.3.0, check it out!
