### ISSUE TITLE
CSS Pseudo-elements broken after upgrading to 1.3.0

### ISSUE THREAD

**Issue by travisbotello** [icons8/line-awesome#27]
After upgrading from 1.1.0 to 1.3.0 my pseudo-elements are broken, e.g.

```
.menu-sec nav > ul > li.menu-item-has-children > a::before {
    content: "\f107";
    font-family: lineawesome;
}
```

Also tried `font-family: 'Line Awesome Free'`

Am I missing something here?

**Comment by travisbotello** [comment]
`font-family: 'Line Awesome Free'` is correct but you also have to add `font-weight: 900;`.

**Comment by aboodz** [comment]
I think it's a bug. I checked the font files. Only font files with weight 900 have all the glyphs. Fonts with weight 400 files contain 146 glyphs only.

**Comment by travisbotello** [comment]
Good point! In the meantime `font-weight: 900;` can be used for bypassing this issue.

**Comment by hssamconf** [comment]
font-weight: 900; doesn't work for me

**Comment by travisbotello** [comment]
Are you using the correct unicode for the `content` property? The codes also changed in the newest version. Also make sure that you are using `font-family: "Line Awesome Free";`.  This is a working example for a dropdown indicator I am using with the newest version:

```
li.menu-item-has-children > a::before {
    position: absolute;
    right: 0px;
    width: 10px;
    height: 10px;
    content: "\f107";
    font-family: "Line Awesome Free";
    font-weight: 900;
    font-size: 10px;
    top: 50%;
    margin-top: -4px;
}

**Comment by hssamconf** [comment]
yes the unicode of the right arrow changed from 1.1.0 to 1.3.0 thanks that fix it

**Comment by fatawesome** [comment]
Sorry for late answer. This behavior is the result of upgrading to new version. Hopefully everything is ok for you now :)
