### ISSUE TITLE
Error copying sample website code

### ISSUE THREAD

**Issue by marcelogarbin** [icons8/line-awesome#28]
When trying to copy the icon code on the [line-awesome](https://icons8.com/line-awesome) website it is not doing it correctly, thus missing character. So when trying to copy to the project using this package, the icon will not render.

![line](https://user-images.githubusercontent.com/9335588/70582399-3288e500-1b99-11ea-912b-35452baab732.gif)

Edit.: I almost forgot. Thanks for the package, I really enjoyed it!

**Comment by fatawesome** [comment]
Wow, that's funny. Will be fixed soon, thank you!

**Comment by fatawesome** [comment]
Fixed. @marcelogarbin check it out :)

**Comment by marcelogarbin** [comment]
all right thank you very much
