### ISSUE TITLE
far fa-heart

### ISSUE THREAD

**Issue by xelaz** [icons8/line-awesome#32]
Hey your icons are nice, but one icon is missing, the far fa-heart :)

**Comment by fatawesome** [comment]
Hey @xelaz! Can you give more information on how to reproduce the problem?

**Comment by xelaz** [comment]
You have not this icon: https://fontawesome.com/icons/heart?style=regular, because it is vey popular.

**Comment by fatawesome** [comment]
Hello @xelaz! We've informed the designers, icon will be added. Thank you!

**Comment by fatawesome** [comment]
Hello there! Try `lar la-heart` :)
