### ISSUE TITLE
Circle inconsistent

### ISSUE THREAD

**Issue by rcnza** [icons8/line-awesome#34]
The line thickness on circle is less than the line thickness used on the circles around *-circle, eg question-circle.  The effect is that, when overlaying a circle on other characters, such as save and using together with eg question-circle, an inconsistent interface is created.

Suggestion: increase the line thickness of circle to match that of circle-notch, or add a thicker circle that is the same as circle-notch without the notch.  Alternatively, if using bold with the current circle will give the same line width as circle-notch, that will help too.

![circles](https://user-images.githubusercontent.com/59911079/72415889-65f8f980-376d-11ea-8d23-e1b97a042a03.png)

Note: this is when using the solid ttf font in Windows.  The svg files seem to show the circles with the same line width

**Comment by fatawesome** [comment]
Hello @rcnza! Designers were informed, fix will be released soon.

**Comment by fatawesome** [comment]
Hello! Try `lar la-circle`. It is thicker ;)
