### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by Sumurai8** [icons8/line-awesome#35]
There does not seem to be a github project to change the documentation, so I will try to outline the problems with [this documentation page](https://icons8.com/line-awesome/howto) here.

As shown in the comments, as well as [a question someone asked on Stackoverflow](https://stackoverflow.com/q/55618401/2209007), it is completely unclear to people why sometimes `.la`-classes are not working. In my eyes, there are two things that can be improved in the current documentation:

- Both CDN links currently look identical, because the actual important thing is cut off. Because they look identical, in people's minds they *are* identical, even if they are not. At the very least, text should be added that describes what each of the links do. Something like: "This is a drop-in for fontawesome and only defines styles with the `.fa`-prefix. It will not add any `.la`-variants" and "This will add styling for all `.la`-variants of the icons.".
- The first link falsely suggests that you will be using Line Awesome. Sure, the CDN is hosted by Line Awesome, and you probably serve your own versions of each of the icons, but any attempt at actually using the icons as described in the documentation will lead to nothing happening and frustrating experiences for people wanting to switch over. One way of preventing that is making the first CDN link actually a transition-link, that defines both `.fa`-styles and `.la`-styles. Another way would be to make it extra clear that you need to use both CDN-links if you want to transition an existing application to `.la`-styling.

**Comment by fatawesome** [comment]
Hello @Sumurai8. Thank you for comment. We understand that documentation is unclear in some places. We will improve it with next Line Awesome release.
