### ISSUE TITLE
Line Awesome is now included in Quasar Framework & QIconPicker

### ISSUE THREAD

**Issue by tohagan** [icons8/line-awesome#37]
This is not a change request ... Just a friendly heads up that I submitted [a feature request](https://github.com/quasarframework/quasar/issues/6164) to [Quasar framework](https://quasar.dev/) to include Line Awesome among it's pre-configured Icon sets which they've kindly [released in Quasar v1.8.0 this week](https://forum.quasar-framework.org/topic/5125/quasar-v1-8-0-released-a-lot-of-new-stuff-and-many-improvements).  It's also now include in [QIconPicker](https://github.com/quasarframework/quasar-ui-qiconpicker) a Quasar app extension.

Quasar's QIcon component has a [rich set of icon features](https://quasar.dev/vue-components/icon) that includes a [new cool new trick](https://quasar.dev/vue-components/icon#Svg-icons) that supports webpack tree shaking of iconsets so just the icons in used by an application are added to the app build avoiding a full web font download. They also support [icon mapping](https://quasar.dev/vue-components/icon#Custom-mapping).

Thanks enormously for releasing Line Awesome and I hope this framework addition will find you new supporters and other linkages to Icons8 products.  I don't represent the Quasar Framework team in any way.  Honestly ... No tats or drugs here dude :grin: and ... seriously FA's **otter** icon just does not compare.

**Comment by fatawesome** [comment]
Wow, that's breathtaking :D Thank you!
