### ISSUE TITLE
.lal is missing font definition

### ISSUE THREAD

**Issue by theolivenbaum** [icons8/line-awesome#40]
It seems like the .lal class [exists in the CSS file](https://github.com/icons8/line-awesome/blob/master/dist/line-awesome/css/line-awesome.css#L4), but doesn't have the font-definition like the [other classes ](https://github.com/icons8/line-awesome/blob/master/dist/line-awesome/css/line-awesome.css#L4405).

**Comment by theolivenbaum** [comment]
Also just to add to that, it seems like most light-weight icons are missing - this is how the demo website shows if one replaces the .las with the font-weight for .lar
![image](https://user-images.githubusercontent.com/8791811/74259933-fb4dc600-4cf8-11ea-86bf-e562e3c203e3.png)

Would be nice to have a fallback to the same icons at font weight 900 on the font...

**Comment by fatawesome** [comment]
The reason for such behavior is that in general icon is not present in all styles. To see styles available for a specific icon check the [reference page](https://icons8.com/line-awesome)
If I misunderstood your point please let me know :)
