### ISSUE TITLE
Icon search displays icons multiple times

### ISSUE THREAD

**Issue by tohagan** [icons8/line-awesome#42]
The icon search feature is great but I tend to get a bit cross-eyed with all the duplicate icons displayed in the search output.

Searching at https://icons8.com/line-awesome

**Comment by flohw** [comment]
Additionally it would be useful to add a filter to search and display only regular/solid/brand icons as fontawseome search engine allows.

I searched for "star" and only saw the solid version and thought that the regular version doesn't exist but it does.

Thank you

**Comment by fatawesome** [comment]
Yep, we have a bug on the page, will be fixed.
About style filter: actually good idea, we will consider it. Thanks!

**Comment by fatawesome** [comment]
Search was fixed :)

**Comment by flohw** [comment]
![2020-03-31-093231_1245x760_scrot](https://user-images.githubusercontent.com/457663/78000976-5aad7700-7335-11ea-8a7b-0fd518fbb2cf.png)
Is there some cache? Or maybe still the bug present or the fix not deployed yet? What about the filters? May I open another issue for that?

Thanks :-)
