### ISSUE TITLE
Missing "la" CSS rules for many brand icons

### ISSUE THREAD

**Issue by scrobbleme** [icons8/line-awesome#44]
Hello,

I'm using Line Awesome via NPM and without Font Awesome.
It looks, like there are some "la" rules missing for brand icons (some have these rules)

I.e. 

`<i class="la la-battle-net"></i>`

won't work.

If this is intended, than it would be great to have some json containing a list and category of all icons within the dist. As of now, someone has to exactly know, what is there.

![image](https://user-images.githubusercontent.com/504835/75519001-8a015900-5a02-11ea-956b-d469e4c3f6b3.png)

**Comment by fatawesome** [comment]
Some have and some not. "la" prefix works for old icons (from old LA versions). Now the preferable way of using icons is with "las", "lab" or "lar" prefixes
For the given example: `<i class="lab la-battle-net"></i>`

Please let me know if this hepled you.

**Comment by scrobbleme** [comment]
@fatawesome Thank you for the clarification.

But is there a way to find out, which icons need las, lab or lar?

From the [npm package](https://www.npmjs.com/package/line-awesome) there is no chance. No json or so containing information about this.

Or can I just use the icons.json from Font Awesome and replace fab with lab i.e.?

This would be really helpful (so I can process it automatically).

**Comment by fatawesome** [comment]
Well, you can replace icons.json, but I recommend using https://icons8.com/line-awesome. There you can find every icon with their classes respectively.

Actually, making a list in readme or in some .json file is a good idea, we will consider it, thanks :)

**Comment by scrobbleme** [comment]
> Actually, making a list in readme or in some .json file is a good idea, we will consider it, thanks :)

That would be great, as we need to process the font automatically (whenever an update happens).
We have customer request to embed the font into our [CF](https://marketplace.atlassian.com/apps/1215716/font-icons-for-confluence?hosting=server&tab=overview) plugin. As of now, it just the missing information. 
But maybe I can process FAs icons.json for the meantime ;)

Thanks, for your support.
