### ISSUE TITLE
Please add Sunset and Sunrise

### ISSUE THREAD

**Issue by adrianvintu** [icons8/line-awesome#46]
Hi guys,

Thank you for your awesome work!

Can you add the [sunset](https://icons8.com/icon/17477/sunset) and [sunrise](https://icons8.com/icon/17476/sunrise) icons, like in the Icon 8 Windows Icon pack?

Please don't make it identical, but please make it sexy, as you usually do! :D

Thank you so much!

**Comment by fatawesome** [comment]
Request was passed to designers :)

**Comment by adrianvintu** [comment]
@fatawesome muchas gracias! :D

To make it clearer: I wish to represent the times of day as follows:
morning: sung going up
afternoon: sun
evening: sun going down
night: moon

I already use the Material icons for
afternoon/sunny `weatherSunny = _MdiIconData(0xf599);`
and night/ `moonWaningCrescent = _MdiIconData(0xff82);`
https://cdn.materialdesignicons.com/1.9.32/


Now that I look at the weatherSunny Material, it looks quite ugly :D

If you think designing all 3 sun icons would be better, please go ahead :)

Thank you for your awesome icons and work!

**Comment by fatawesome** [comment]
Unfortunately, we can't add such icons in near future
But everything can change :) Stay in touch!

**Comment by adrianvintu** [comment]
So sorry to hear that. Any reason why?

**Comment by fatawesome** [comment]
Mainly because Line Awesome is a replacement for free tier Font Awesome, while icons you showed are from _pro_ set. 
Also, our designers are busy creating our main icons (check em out on https://icons8.com/icons)

**Comment by adrianvintu** [comment]
Thank you, I don't really know too much about these fonts. I will consider dropping LineAwsome then, and go with some pngs.

Thank you.
