### ISSUE TITLE
No full circle

### ISSUE THREAD

**Issue by jknigga** [icons8/line-awesome#47]
I was looking to replace font awesome with line awesome and noticed that the the "la-circle" was just an outline. Which, makes sense but I see that there is a "la-square-full". I use the circle for indicators and having a filled circle would be great!

**Comment by fatawesome** [comment]
Line Awesome was designed to be, well, 'line' font. The idea of such style is not having fully filled icons. 
But I will pass your request to designers, lets see what they say :)

**Comment by jknigga** [comment]
@fatawesome - I understand that and actually wasn't going to suggest anything, but there was a full square so I figured I would ask!

**Comment by fatawesome** [comment]
Right now we don't plan to add such icon, sorry :(

**Comment by NicoHood** [comment]
I am also missing the full circle. It can be used to stack items. Currently this is only possible with the square.
