### ISSUE TITLE
Site menu does not work correctly in firefox

### ISSUE THREAD

**Issue by sashabeep** [icons8/line-awesome#48]
Every menu item just bumping page to the top
![Mar-27-2020 15-12-07](https://user-images.githubusercontent.com/5689796/77755138-af06dd00-703d-11ea-898a-bc1fec32efb2.gif)

Copy-pasted link is also opens top scroll position.
Issue not reproducing in safari and chrome.
FF 74.0 MAC OS

**Comment by fatawesome** [comment]
Wow, I will definitely have a look, thanks

**Comment by fatawesome** [comment]
Fixed, thank you!
