### ISSUE TITLE
TikTok Icon

### ISSUE THREAD

**Issue by thagxt** [icons8/line-awesome#51]
Hi Guys,
Would it be possible to add the TikTok Logo icon?!

**Comment by fatawesome** [comment]
See https://github.com/icons8/line-awesome/pull/53

**Comment by fatawesome** [comment]
Also, check this out: https://icons8.com/icons/set/tiktok-logo

**Comment by thagxt** [comment]
Cool! but I needed it inside the line awesome font not standalone image...
