### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by imprathamesh** [icons8/line-awesome#58]
Article
Dashboard 
add more icons similar to remixicon.com.

**Comment by visualpharm** [comment]
There are all of them, although not open source: [Dashboards](https://icons8.com/icon/set/dashboard/windows), [Bunch of articles](https://icons8.com/icon/set/article/windows), etc.

Our hope was that after you outgrow Line Awesome, you look into Icons8, either free or not. And boy it's [huge](https://icons8.com/icons/windows). 

What we're going to do however is to add more free styles.
