### ISSUE TITLE
How to use Line-Awesome icon font in Ionic 3 app?

### ISSUE THREAD

**Issue by prashantweb** [icons8/line-awesome#7]
I am trying to use Line-Awesome icon font in my ionic 3 project but can't make it work. I have followed few tutorials like this - https://www.joshmorony.com/including-custom-css-files-in-the-ionic-build-process/

Can someone guide me to use proper method to make it work? This is the link of line awesome icon fonts based on Fontawesome https://github.com/icons8/line-awesome

Error i am getting - 
![sass_error](https://user-images.githubusercontent.com/10391863/34199946-599b98f4-e595-11e7-83bf-da664dd90384.jpg)

**Comment by fitodac** [comment]
Maybe you should load the LA css file in the head of your html.
LineAwesome works exactly as same way as Font Awesome works.
I wish this helped you.

**Comment by diyen1** [comment]
I got it to work by using font-awesome classes.

For example `<i class="la la-bars"></i>` should be `<i class="fa fa-bars"></i>`

**Comment by fatawesome** [comment]
Good job! If you still have any issues, feel free to contact us :)
