### ISSUE TITLE
icon request: pause-circle

### ISSUE THREAD

**Issue by Hongbo-Miao** [icons8/line-awesome#8]
Right now line-awesome has play-circle. But it does not have pause-circle.

The reason I request this is because a player when you click play button, it will change to pause button. However, right now the style is not consistent, because one has circle, the other does not have. I hope both can have the circle version.

Thanks!

**Comment by fitodac** [comment]
Hi @Hongbo-Miao, you are right. I try to fix this mistake on the next pull request.
thanks

**Comment by fatawesome** [comment]
Hello! The new pack we've recently released contains this icon :)
