### ISSUE TITLE
Icon Request : american-sign-language-interpreting

### ISSUE THREAD

**Issue by pierrerocket** [icons8/line-awesome#9]
Hello, 

I noticed this icon was missing from Line Awesome.  Is there a way to fall back to font awesome if the icon isn't present in the line awesome set?

**Comment by fatawesome** [comment]
Hello! You can use Line Awesome and Font Awesome alongside each other. By the way, we've just released the new version of Line Awesome, see if you can find the desired icon in a new pack :)
